apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: mywebapp
  name: mywebapp
spec:
  containers:
  - image: amitvashist7/mypython-web-app:v1
    name: mywebapp
    ports:
    - containerPort: 8081
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
