apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-sleeper-3
spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 5000
  containers:
  -  name: ubuntu-sleeper-3
     image: ubuntu
     command: ["sleep", "5000"]
