apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-sleeper
spec:
  securityContext:
    runAsUser: 1000
  containers:
  -  name: ubuntu-sleeper-1
     image: ubuntu
     command: ["sleep", "5000"]
  -  name: ubuntu-sleeper-2
     image: ubuntu
     command: ["sleep", "5000"]
     securityContext:
       runAsUser: 2000
